In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Concepts and technology of AI/w6/Houseprice.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   HouseAge    100 non-null    int64  
 1   HouseFloor  100 non-null    int64  
 2   HouseArea   100 non-null    float64
 3   HousePrice  100 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB


In [ ]:
hAge = df['HouseAge'].to_numpy()
hFloor = df['HouseFloor'].to_numpy()
hArea = df['HouseArea'].to_numpy()
hPrice = df['HousePrice'].to_numpy()

In [ ]:
x0 = np.ones(len(hAge))
X = np.array([x0, hAge, hFloor, hArea]).T

X2 = np.array([x0, hFloor, hArea, hPrice]).T

X2


array([[1.00000000e+00, 2.00000000e+00, 1.12945574e+02, 5.43917180e+05],
       [1.00000000e+00, 1.00000000e+00, 1.74312126e+02, 8.17740125e+05],
       [1.00000000e+00, 4.00000000e+00, 1.25219577e+02, 3.87992503e+05],
       [1.00000000e+00, 4.00000000e+00, 1.21210124e+02, 2.40840742e+05],
       [1.00000000e+00, 4.00000000e+00, 5.92217368e+01, 2.77273387e+05],
       [1.00000000e+00, 5.00000000e+00, 2.02391083e+02, 6.62664128e+05],
       [1.00000000e+00, 1.00000000e+00, 1.75669756e+02, 8.52475560e+05],
       [1.00000000e+00, 5.00000000e+00, 6.28696878e+01, 2.98786837e+05],
       [1.00000000e+00, 5.00000000e+00, 1.19661616e+02, 5.38040702e+05],
       [1.00000000e+00, 1.00000000e+00, 2.77066471e+02, 7.91378690e+05],
       [1.00000000e+00, 1.00000000e+00, 1.09890473e+02, 3.37936660e+05],
       [1.00000000e+00, 1.00000000e+00, 8.62237180e+01, 3.82611941e+05],
       [1.00000000e+00, 1.00000000e+00, 1.72363190e+02, 5.06203444e+05],
       [1.00000000e+00, 4.00000000e+00, 2.96412614e

In [ ]:
W = np.array([0,0,0,0])
Y = np.array(hPrice)
print(Y)

[ 543917.17984142  817740.12482771  387992.50301932  240840.74238818
  277273.38652523  662664.12812989  852475.55964824  298786.83701346
  538040.70198319  791378.68966438  337936.65959035  382611.94113683
  506203.44357455  743244.59111291  403430.33569623 1043108.16601744
  982596.73666629  397128.89979871  528758.78197003  541984.6137248
 1033973.60932934  497937.99690719  647917.71919826  334064.20550363
 1089540.94675596  525033.95964725  391101.58149165  183104.97039435
  560696.25994893  966582.06035172  230789.44046813  813223.66347791
  501167.81565254  737515.9067797   321996.36274989  970892.3448663
  577885.28215608 1160625.0947274   364007.9919224   626997.13255948
  230001.15960568  874058.62161555  609107.50841373  421184.72563993
  452874.35954963  858723.58041113  684254.65720567  519531.5319317
  409421.91774218  149356.16465988  577542.14489665 1228712.41166859
  632707.23982857  314881.94671331  488320.5363306   996812.76682397
  717139.72766151 1046095.04718271  5

In [ ]:
def cost_function(X, Y, W):
    """ Parameters:
    This function finds the Mean Square Error.
    Input parameters:
      X: Feature Matrix
      Y: Target Matrix
      W: Weight Matrix
    Output Parameters:
      J: accumulated mean square error.
    """
    m = len(Y)

    J = np.sum((X.dot(W) - Y) ** 2)/(2 * m)
    return J

In [ ]:
# Test case
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])

cost = cost_function(X_test, Y_test, W_test)


if cost == 0:
    print("Proceed Further")
else:
    print("Something went wrong: Reimplement the cost function")
    print("Cost function output:", cost)

Proceed Further


In [ ]:
initial_cost = cost_function(X2, Y, W)
print(initial_cost)

201528080199.132


In [ ]:
def gradient_descent(X, Y, B, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)

    for iteration in range(iterations):

        Y_pred = X.dot(B)

        loss = Y_pred - Y

        dw = (X.T.dot(loss) ) / (m)

        W_update = W - alpha * dw

        cost = cost_function(X2, Y, W_update)
        cost_history[iteration] = cost

    return W_update, cost_history


In [ ]:
alpha = 0.0001
new_weights, cost_history = gradient_descent(X2, Y, W, alpha, iterations=1000)


print("New weights:", new_weights)


print("Cost history:", cost_history[-3:])

New weights: [5.79096447e+01 1.63668584e+02 1.13470948e+04 4.03056160e+07]
Cost history: [3.2739100404142954e+26, 3.2739100404142954e+26, 3.2739100404142954e+26]


In [ ]:
def rmse(Y, Y_pred):
  """
  This Function calculates the Root Mean Squres.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rmse: Root Mean Square.
  """
  rmse = np.sqrt(sum((Y-Y_pred)**2)/len(Y))
  return rmse


In [ ]:
def r2(Y, Y_pred):
  """
   This Function calculates the R Squared Error.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rsquared: R Squared Error.
    """
  mean_y = np.mean(Y)
  ss_tot = sum((Y - mean_y) ** 2)
  ss_res = sum((Y - Y_pred) ** 2)
  r2 = 1 - (ss_res / ss_tot)
  return r2


In [ ]:
Y_pred = X2.dot(new_weights)

print(rmse(Y, Y_pred))
print(r2(Y, Y_pred))

25588708605219.984
-9671321841354916.0


**Logistic**

In [6]:

X = df.drop('HouseFloor', axis=1)
y = df['HouseFloor']



In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [10]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [11]:

model = LogisticRegression(max_iter=1000) # Increased max_iter to ensure convergence
model.fit(X_train, y_train)


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [12]:
y_pred = model.predict(X_test)

In [13]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [14]:
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

Accuracy: 0.25
Confusion Matrix:
[[4 0 0 3 0]
 [3 0 2 1 0]
 [2 0 0 1 0]
 [1 0 0 1 0]
 [1 0 0 1 0]]
Classification Report:
              precision    recall  f1-score   support

           1       0.36      0.57      0.44         7
           2       0.00      0.00      0.00         6
           3       0.00      0.00      0.00         3
           4       0.14      0.50      0.22         2
           5       0.00      0.00      0.00         2

    accuracy                           0.25        20
   macro avg       0.10      0.21      0.13        20
weighted avg       0.14      0.25      0.18        20

